checkout: git clone --recursive https://github.com/edwardstock/miledger.git .

commands:
  build_and_package:
    steps:
      - run: bash cfg/package_make.sh -t appimage

  make_project:
    steps:
      - build_and_package

  init_deb:
    steps:
      - run: apt -y update
      - run: apt -y install gcc g++ python3 python3-pip curl git
      - run: pip3 install --upgrade pip
      - run: pip3 install --upgrade setuptools
      - run: pip3 install conan
      - run: apt -y install libusb-1.0 libudev-dev
      - run: apt -y install --no-install-recommends  libgl1-mesa-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev xkb-data xorg-dev
      - run: bash cfg/setup.sh

jobs:
  ubuntu_18.04:
    image: ubuntu:18.04
    steps:
      - init_deb
      - make_project


