name: Build on Linux

on:
  push:
    branches:
      - master
jobs:
  build_and_package:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup system
        run: |
          sudo apt -y update
          sudo apt -y install gcc-8 g++ python3 python3-pip curl git
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools
          pip3 install --upgrade requests
          pip3 install conan
          sudo apt -y install libusb-1.0 libudev-dev
          sudo apt -y install --no-install-recommends  libgl1-mesa-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev xkb-data xorg-dev
          sudo bash cfg/setup.sh
      - name: Build & Package
        run: bash cfg/package_make.sh -t appimage
      - name: Upload release to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _build/*.AppImage
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

