name: Build on Linux

on:
  push:
    branches:
      - master
jobs:
  build_and_package:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup system
        run: |
          sudo apt -y update
          sudo apt -y install gcc g++ python3 python3-pip curl git
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools
          pip3 install --upgrade requests
          pip3 install conan
          sudo apt -y install libusb-1.0 libudev-dev
          sudo apt -y install --no-install-recommends  libgl1-mesa-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev xkb-data xorg-dev
          sudo bash cfg/setup.sh
      - name: Build & Package
        run: bash cfg/package_make.sh -t appimage
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: _build/*.AppImage
